[Unit]
After=NetworkManager.service
Wants=NetworkManager.service

[Service]
TimeoutStartSec=120
ExecStartPre=/usr/bin/bash -c 'until ip -4 addr show dev wlan0 | grep -Fq "inet 192.168.8.18/"; do sleep 1; done'
