import { existsSync } from 'node:fs'; import { connect, createServer, type Server } from 'node:net'; import { config } from '../config.js'; import type { LogEntry, Phase, Status, TeleopMode } from '../types.js'; import { ProcessManager } from './ProcessManager.js'; import { SSHService } from './SSHService.js'; import { ensureDdsReady, g1Reachable, interfaceAddress, tcp } from './NetworkService.js'; import { IPCService } from './IPCService.js';
export class Orchestrator {
  phase:Phase='idle'; mode:TeleopMode='motion'; lastError?:string; camera?:Awaited<ReturnType<SSHService['stream']>>; cameraServiceStopped=false; cameraSource:'dji'|'native'|'none'='none'; webrtcProxy?:Server; logs:LogEntry[]=[]; questConnected=false;
  processes=new ProcessManager(e=>this.addLog(e)); ssh=new SSHService(); ipc=new IPCService(); constructor(private emit:(event:string,data:unknown)=>void){}
  addLog(e:LogEntry){if(!e.message)return;const lower=e.message.toLowerCase();if((lower.includes('brokenpipeerror')||lower.includes('connectionreseterror'))&&lower.includes('web_fileresponse.py'))return;if(lower.includes('websocket is connected')){this.questConnected=true;this.emit('quest:status',{ok:true,label:'CONECTADO',detail:'WebSocket do Quest ativo'});}if(lower.includes('websocket is now disconnected')||lower.includes('websocket connection closed')){this.questConnected=false;this.emit('quest:status',{ok:false,label:'AGUARDANDO',detail:'WebSocket do Quest desconectado'});}this.logs.push(e);this.logs=this.logs.slice(-600);this.emit(`${e.source}:log`,e);}
  error(e:unknown){this.lastError=e instanceof Error?e.message:String(e);this.phase='error';this.emit('system:error',{message:this.lastError});this.addLog({time:new Date().toISOString(),source:'system',level:'error',message:this.lastError});}
  async status():Promise<Status>{const [g1,cfg,webrtc,zmq,vuer]=await Promise.all([g1Reachable(),tcp(config.g1Host,config.configPort),tcp(config.g1Host,config.webrtcPort),tcp(config.g1Host,config.zmqPort),tcp('127.0.0.1',config.vuerPort)]);if(!vuer)this.questConnected=false;const cameraReady=cfg&&(webrtc||zmq);if(!cameraReady&&this.phase==='idle')this.cameraSource='none';const cameraLabel=cameraReady?(this.cameraSource==='dji'?'ATIVA COM DJI':this.cameraSource==='native'?'ATIVA COM CÂMERA NATIVA':'ATIVA'):'SEM CÂMERA';const eth=interfaceAddress(config.networkInterface); const s:Status={timestamp:new Date().toISOString(),phase:this.phase,mode:this.mode,g1:{ok:g1,label:g1?'ONLINE':'OFFLINE',detail:config.g1Host},ethernet:{ok:eth==='192.168.123.99',label:eth?'CONECTADA':'DESCONECTADA',detail:eth??config.networkInterface},quest:{ok:this.questConnected,label:this.questConnected?'CONECTADO':'AGUARDANDO',detail:this.questConnected?'WebSocket do Quest ativo':'Abra a URL no headset'},camera:{ok:cameraReady,label:cameraLabel,detail:cameraReady?(webrtc?`WebRTC ${config.webrtcPort}`:`ZMQ ${config.zmqPort}`):'Teleoperação disponível sem vídeo'},vuer:{ok:vuer,label:vuer?'EXECUTANDO':'PARADO',detail:`porta ${config.vuerPort}`},ssh:{ok:existsSync(config.sshKey),label:existsSync(config.sshKey)?'CHAVE ENCONTRADA':'SEM CHAVE',detail:config.sshKey},teleopPid:this.processes.get('teleop')?.pid,cameraPid:undefined,lastError:this.lastError};this.emit('system:status',s);return s;}
  async prepare(mode:TeleopMode){if(this.processes.isRunning('teleop'))throw new Error('Teleoperação já preparada');this.mode=mode;this.phase='preparing';this.lastError=undefined;this.questConnected=false;try{if(!(await g1Reachable()))throw new Error('G1 não responde em '+config.g1Host);if(!(await ensureDdsReady()))throw new Error('Não foi possível estabelecer automaticamente a comunicação DDS com o G1.');const cameraReady=await this.startCamera();const args=['-u','teleop_hand_and_arm.py','--ipc',`--input-mode=${mode==='hands'?'hand':'controller'}`,'--display-mode=immersive','--arm=G1_29',`--img-server-ip=${config.g1Host}`,`--webrtc-server-ip=${config.webrtcProxyHost}`,`--network-interface=${config.networkInterface}`];if(!cameraReady)args.push('--no-camera');if(mode==='motion')args.push('--motion');this.processes.start('teleop',config.pythonPath,args,config.teleopPath,{...process.env,PYTHONUNBUFFERED:'1'});await this.ipc.waitForReady();if(!this.processes.isRunning('teleop'))throw new Error('O processo de teleoperação encerrou durante a preparação. Consulte os logs.');this.phase='ready';}catch(e){await this.processes.stop('teleop').catch(()=>{});this.error(e);await this.restoreCamera().catch(()=>{});throw e;}}
  async activate(){if(this.phase!=='ready')throw new Error('Prepare o sistema antes de ativar');await this.ipc.waitForMotion();await this.ipc.send('CMD_START');this.phase='active';this.addLog({time:new Date().toISOString(),source:'system',level:'info',message:'Movimento ativado com poses XR válidas'});}
  async stop(){this.phase='stopping';try{if(this.processes.isRunning('teleop')){try{await this.ipc.send('CMD_STOP');}catch(e){this.addLog({time:new Date().toISOString(),source:'system',level:'error',message:`IPC de parada indisponível; usando SIGINT seguro: ${e instanceof Error?e.message:String(e)}`});this.processes.signal('teleop','SIGINT');}}await this.processes.stop('teleop');this.questConnected=false;await this.restoreCamera();this.phase='idle';}catch(e){this.error(e);throw e;}}
  async startCamera():Promise<boolean>{
    const ready=async()=>await tcp(config.g1Host,config.configPort)&&(await tcp(config.g1Host,config.webrtcPort)||await tcp(config.g1Host,config.zmqPort));
    if(await ready()){this.cameraSource='native';if(await tcp(config.g1Host,config.webrtcPort))await this.startWebrtcProxy();return true;}
    // video_hub exposes/initializes the native RealSense USB devices. It must
    // run briefly before camera discovery, even though TeleImager later owns them.
    await this.ssh.exec('sudo -n /unitree/sbin/mscli startservice video_hub_pc4',5000).catch(()=>{});
    await new Promise(resolve=>setTimeout(resolve,2000));
    const devices=await this.ssh.exec(`bash -lc 'for d in /sys/class/video4linux/video*/name; do test -r "$d" && printf "%s: " "$d" && cat "$d"; done'`,5000).catch(()=>({stdout:'',stderr:'',code:1}));
    const hasCamera=devices.stdout.trim().length>0;
    const hasDji=/dji|osmo/i.test(devices.stdout);
    const hasNative=/realsense|intel\(r\).*depth/i.test(devices.stdout);
    if(hasCamera){
      await this.ssh.exec('sudo -n /unitree/sbin/mscli stopservice video_hub_pc4');this.cameraServiceStopped=true;
      const profile=hasDji?'cam_config_dji.yaml':hasNative?'cam_config_realsense.yaml':undefined;
      if(profile)await this.ssh.exec(`cp ${config.teleimagerPath}/${profile} ${config.teleimagerPath}/cam_config_server.yaml`,5000);
      // Both DJI and the native D435i color stream are consumed through their
      // UVC/OpenCV nodes. This avoids requiring pyrealsense2 on the Jetson.
      const py=`import sys; import teleimager.image_server as m; m.reload_uvc_driver=lambda: None; sys.argv=['teleimager.image_server']; m.main()`;
      const encoded=Buffer.from(py).toString('base64');
      const robotTls=config.webrtcProxyHost==='192.168.3.10'?'XR_TELEOP_CERT=/home/unitree/.config/xr_teleoperate/robot-cert.pem XR_TELEOP_KEY=/home/unitree/.config/xr_teleoperate/robot-key.pem ':'';
      const cmd=`bash -lc 'source ~/miniconda3/etc/profile.d/conda.sh && conda activate teleimager && cd ${config.teleimagerPath} && printf %s ${encoded} | base64 -d | ${robotTls}python -u -'`;
      this.camera=await this.ssh.stream(cmd,(message,error)=>this.addLog({time:new Date().toISOString(),source:'camera',level:error?'error':'info',message:message.trimEnd()}));
      const deadline=Date.now()+config.cameraStartupTimeoutMs;while(Date.now()<deadline&&!await ready())await new Promise(resolve=>setTimeout(resolve,500));
      if(await ready()){this.cameraSource=hasDji?'dji':'native';if(await tcp(config.g1Host,config.webrtcPort))await this.startWebrtcProxy();this.lastError=undefined;this.addLog({time:new Date().toISOString(),source:'system',level:'info',message:this.cameraSource==='dji'?'Câmera ativa com DJI':'Câmera nativa ativa'});return true;}
    }
    await this.restoreCamera().catch(()=>{});
    // The Unitree service is the native-camera fallback. Starting an already
    // running service is harmless and also recovers state after an API restart.
    await this.ssh.exec('sudo -n /unitree/sbin/mscli startservice video_hub_pc4',5000).catch(()=>{});
    const nativeDeadline=Date.now()+8000;while(Date.now()<nativeDeadline&&!await ready())await new Promise(resolve=>setTimeout(resolve,500));
    if(await ready()){this.cameraSource='native';if(await tcp(config.g1Host,config.webrtcPort))await this.startWebrtcProxy();this.addLog({time:new Date().toISOString(),source:'system',level:'info',message:'Câmera nativa ativa'});return true;}
    this.cameraSource='none';this.addLog({time:new Date().toISOString(),source:'system',level:'info',message:'Nenhuma câmera disponível; teleoperação seguirá sem vídeo em pass-through'});return false;
  }
  async startWebrtcProxy(){if(this.webrtcProxy)return;this.webrtcProxy=createServer(client=>{const upstream=connect(config.webrtcPort,config.g1Host);client.pipe(upstream);upstream.pipe(client);const close=()=>{client.destroy();upstream.destroy();};client.on('error',close);upstream.on('error',close);client.on('close',close);upstream.on('close',close);});await new Promise<void>((resolve,reject)=>{this.webrtcProxy!.once('error',reject);this.webrtcProxy!.listen(config.webrtcPort,'0.0.0.0',()=>{this.webrtcProxy!.off('error',reject);resolve();});});}
  async restoreCamera(){if(this.webrtcProxy){const proxy=this.webrtcProxy;(proxy as Server & {closeAllConnections?:()=>void}).closeAllConnections?.();await Promise.race([new Promise<void>(resolve=>proxy.close(()=>resolve())),new Promise<void>(resolve=>setTimeout(resolve,750))]);this.webrtcProxy=undefined;}if(this.camera){const camera=this.camera;this.camera=undefined;await this.ssh.exec(`bash -lc 'pid=$(ss -ltnp "sport = :${config.configPort}" | sed -n "s/.*pid=\\([0-9]*\\).*/\\1/p" | head -1); if [[ "$pid" =~ ^[0-9]+$ ]]; then kill -INT "$pid"; fi'`,4000).catch(()=>{});camera.stream?.close();camera.client?.end();}if(this.cameraServiceStopped){await this.ssh.exec('sudo -n /unitree/sbin/mscli startservice video_hub_pc4',4000);this.cameraServiceStopped=false;this.addLog({time:new Date().toISOString(),source:'system',level:'info',message:'Serviço video_hub_pc4 restaurado'});}}
}
